/* ========================================
   IDEA AGENT — Store Module
   localStorage wrapper + data persistence
   ======================================== */

var Store = {
  STORAGE_KEY: 'idea-agent-data',
  DATA_VERSION: 1,

  // Default data structure
  defaults: {
    version: 1,
    settings: {
      theme: 'dark',
      defaultCategory: 'tech',
      autoGenerateDraft: false,
      geminiApiKey: '',
      geminiModel: 'gemini-2.5-flash',
    },
    ideas: [],
    tags: ['AI', 'research', 'surgery', 'NCKH', 'app', 'clinical', 'workflow', 'automation'],
    stats: {
      totalIdeas: 0,
      totalDrafts: 0,
      lastCaptureDate: null,
    }
  },

  // Initialize store
  init() {
    let data = this.load();
    if (!data || data.version !== this.DATA_VERSION) {
      data = { ...this.defaults };
      this.save(data);
    }
    return data;
  },

  // Load from localStorage
  load() {
    try {
      const raw = localStorage.getItem(this.STORAGE_KEY);
      return raw ? JSON.parse(raw) : null;
    } catch (e) {
      console.error('Store.load error:', e);
      return null;
    }
  },

  // Save to localStorage
  save(data) {
    try {
      localStorage.setItem(this.STORAGE_KEY, JSON.stringify(data));
    } catch (e) {
      console.error('Store.save error:', e);
    }
  },

  // Get current data
  getData() {
    return this.load() || this.defaults;
  },

  // Update data with merge
  update(partial) {
    const data = this.getData();
    Object.assign(data, partial);
    this.save(data);
    return data;
  },

  // ========================
  // IDEAS CRUD
  // ========================

  // Generate next idea ID for a given date
  generateId(date) {
    const dateStr = this.formatDateId(date);
    const ideas = this.getData().ideas;
    const dayIdeas = ideas.filter(i => i.id.startsWith(dateStr));
    const nextNum = dayIdeas.length + 1;
    return `${dateStr}-${String(nextNum).padStart(3, '0')}`;
  },

  // Format date for ID: YYYY-MM-DD
  formatDateId(date) {
    const d = new Date(date);
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${y}-${m}-${day}`;
  },

  // Add new idea
  addIdea(ideaData) {
    const data = this.getData();
    const now = new Date();
    const id = this.generateId(now);

    const idea = {
      id,
      title: ideaData.title || 'Ý tưởng không tiêu đề',
      summary: ideaData.summary || '',
      content: ideaData.content || '',
      category: ideaData.category || data.settings.defaultCategory,
      tags: ideaData.tags || [],
      priority: ideaData.priority || 'medium',
      status: 'raw',
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      drafts: [],
      linkedIdeas: [],
    };

    data.ideas.unshift(idea);
    data.stats.totalIdeas = data.ideas.length;
    data.stats.lastCaptureDate = now.toISOString();

    // Add new tags to tag list
    if (idea.tags.length) {
      const existingTags = new Set(data.tags);
      idea.tags.forEach(t => existingTags.add(t));
      data.tags = Array.from(existingTags);
    }

    this.save(data);
    return idea;
  },

  // Get idea by ID
  getIdea(id) {
    return this.getData().ideas.find(i => i.id === id) || null;
  },

  // Update existing idea
  updateIdea(id, updates) {
    const data = this.getData();
    const idx = data.ideas.findIndex(i => i.id === id);
    if (idx === -1) return null;

    data.ideas[idx] = {
      ...data.ideas[idx],
      ...updates,
      updatedAt: new Date().toISOString()
    };

    this.save(data);
    return data.ideas[idx];
  },

  // Delete idea
  deleteIdea(id) {
    const data = this.getData();
    data.ideas = data.ideas.filter(i => i.id !== id);
    data.stats.totalIdeas = data.ideas.length;
    this.save(data);
  },

  // Add draft to idea
  addDraft(ideaId, draftContent) {
    const data = this.getData();
    const idea = data.ideas.find(i => i.id === ideaId);
    if (!idea) return null;

    const version = idea.drafts.length + 1;
    const draft = {
      version,
      content: draftContent,
      createdAt: new Date().toISOString(),
    };

    idea.drafts.push(draft);
    idea.status = `draft_v${version}`;
    idea.updatedAt = new Date().toISOString();
    data.stats.totalDrafts = data.ideas.reduce((sum, i) => sum + i.drafts.length, 0);

    this.save(data);
    return draft;
  },

  // ========================
  // QUERY HELPERS
  // ========================

  // Get all ideas sorted by date (newest first)
  getAllIdeas(options = {}) {
    let ideas = [...this.getData().ideas];

    // Filter by category
    if (options.category && options.category !== 'all') {
      ideas = ideas.filter(i => i.category === options.category);
    }

    // Filter by priority
    if (options.priority && options.priority !== 'all') {
      ideas = ideas.filter(i => i.priority === options.priority);
    }

    // Filter by status
    if (options.status && options.status !== 'all') {
      ideas = ideas.filter(i => i.status === options.status || i.status.startsWith(options.status));
    }

    // Search text
    if (options.search) {
      const q = options.search.toLowerCase();
      ideas = ideas.filter(i =>
        i.title.toLowerCase().includes(q) ||
        i.summary.toLowerCase().includes(q) ||
        i.content.toLowerCase().includes(q) ||
        i.tags.some(t => t.toLowerCase().includes(q))
      );
    }

    // Sort
    if (options.sort === 'oldest') {
      ideas.sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
    } else if (options.sort === 'priority') {
      const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 };
      ideas.sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority]);
    } else {
      // Default: newest first
      ideas.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
    }

    return ideas;
  },

  // Group ideas by date
  getIdeasByDate(options = {}) {
    const ideas = this.getAllIdeas(options);
    const groups = {};

    ideas.forEach(idea => {
      const dateKey = idea.id.substring(0, 10); // YYYY-MM-DD
      if (!groups[dateKey]) {
        groups[dateKey] = [];
      }
      groups[dateKey].push(idea);
    });

    return groups;
  },

  // Get today's ideas count
  getTodayCount() {
    const today = this.formatDateId(new Date());
    return this.getData().ideas.filter(i => i.id.startsWith(today)).length;
  },

  // Get ideas for this week
  getWeekCount() {
    const now = new Date();
    const weekAgo = new Date(now);
    weekAgo.setDate(weekAgo.getDate() - 7);

    return this.getData().ideas.filter(i => new Date(i.createdAt) >= weekAgo).length;
  },

  // Get this month's ideas count
  getMonthCount() {
    const now = new Date();
    const monthStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
    return this.getData().ideas.filter(i => i.id.startsWith(monthStr)).length;
  },

  // Get available tags
  getTags() {
    return this.getData().tags || [];
  },

  // Get category counts
  getCategoryCounts() {
    const ideas = this.getData().ideas;
    const counts = { research: 0, clinical: 0, tech: 0, personal: 0, business: 0 };
    ideas.forEach(i => {
      if (counts.hasOwnProperty(i.category)) counts[i.category]++;
    });
    return counts;
  },

  // ========================
  // SETTINGS
  // ========================

  getSettings() {
    return this.getData().settings;
  },

  updateSettings(updates) {
    const data = this.getData();
    data.settings = { ...data.settings, ...updates };
    this.save(data);
    return data.settings;
  },

  // ========================
  // EXPORT / IMPORT
  // ========================

  exportData() {
    return JSON.stringify(this.getData(), null, 2);
  },

  importData(jsonString) {
    try {
      const data = JSON.parse(jsonString);
      if (data.version) {
        this.save(data);
        return true;
      }
      return false;
    } catch (e) {
      console.error('Import error:', e);
      return false;
    }
  },

  // Clear all data
  clearAll() {
    localStorage.removeItem(this.STORAGE_KEY);
  }
};
